// Mock data for the iEducation mobile app

export const offers = [
  {
    id: 1,
    badge: 'Featured',
    title: 'HSC 26 Pre Admission',
    highlight: 'Science Course',
    subtitle: 'Live + recorded classes by top university teachers',
    cta: 'Enroll Now',
    gradient: 'from-brand-700 via-brand-800 to-brand-950',
    emoji: '🎓',
  },
  {
    id: 2,
    badge: 'New Batch',
    title: 'Admission Crash Course',
    highlight: 'Medical & Engineering',
    subtitle: 'IBA, BUET, DU, Medical & University full prep package',
    cta: 'Join Batch',
    gradient: 'from-brand-600 via-brand-800 to-brand-950',
    emoji: '🚀',
  },
  {
    id: 3,
    badge: 'Free Trial',
    title: 'SSC 2026 Full Package',
    highlight: '7 Days Free',
    subtitle: 'Start free, no card required, cancel anytime',
    cta: 'Try Free',
    gradient: 'from-brand-800 via-brand-900 to-brand-950',
    emoji: '📘',
  },
];

export const stats = [
  { id: 1, label: 'Active Students', value: '২,৪০,০০০+', icon: 'Users', color: 'from-brand-500 to-brand-800' },
  { id: 2, label: 'Live Courses', value: '১২০+', icon: 'Radio', color: 'from-accent-400 to-accent-600' },
  { id: 3, label: 'Success Rate', value: '৯৬%', icon: 'TrendingUp', color: 'from-brand-600 to-brand-900' },
  { id: 4, label: 'Video Lectures', value: '১৮,৫০০+', icon: 'PlayCircle', color: 'from-accent-500 to-amber-600' },
];

export const subjects = [
  { id: 'admission', label: 'Admission', emoji: '🎯', sub: 'University & Medical' },
  { id: 'hsc', label: 'HSC', emoji: '📗', sub: 'Class 11 - 12' },
  { id: 'ssc', label: 'SSC', emoji: '📕', sub: 'Class 9 - 10' },
  { id: 'class8', label: 'Class 8', emoji: '📒', sub: 'JSC level' },
  { id: 'lower', label: 'Class 1-7', emoji: '🧮', sub: 'Primary' },
];

export const courseFilters = [
  { id: 'all', label: 'All' },
  { id: 'fbc26', label: 'FBC 26' },
  { id: 'second', label: '2nd Time' },
  { id: 'special', label: 'Special' },
];

export const courses = [
  {
    id: 1,
    title: 'HSC 26 Physics Full Course',
    instructor: 'Tahmid Hasan',
    rating: 4.9,
    students: 12450,
    price: 3499,
    oldPrice: 5999,
    duration: '8 months',
    lectures: 240,
    tag: 'fbc26',
    badge: 'Best Seller',
    gradient: 'from-brand-700 to-brand-950',
    emoji: '⚛️',
  },
  {
    id: 2,
    title: 'Medical Admission Crash',
    instructor: 'Dr. Rifat Ahmed',
    rating: 4.8,
    students: 8230,
    price: 4999,
    oldPrice: 7999,
    duration: '4 months',
    lectures: 180,
    tag: 'special',
    badge: 'Hot',
    gradient: 'from-accent-500 to-amber-600',
    emoji: '🩺',
  },
  {
    id: 3,
    title: 'BUET 2nd Time Engineering',
    instructor: 'Engr. Sajid Khan',
    rating: 4.9,
    students: 5120,
    price: 5999,
    oldPrice: 8999,
    duration: '6 months',
    lectures: 220,
    tag: 'second',
    badge: 'Premium',
    gradient: 'from-brand-600 to-brand-900',
    emoji: '🛠️',
  },
  {
    id: 4,
    title: 'SSC 26 Higher Math Mastery',
    instructor: 'Mahbub Rahman',
    rating: 4.7,
    students: 9870,
    price: 1999,
    oldPrice: 3499,
    duration: '7 months',
    lectures: 160,
    tag: 'fbc26',
    badge: 'New',
    gradient: 'from-brand-500 to-brand-800',
    emoji: '📐',
  },
  {
    id: 5,
    title: 'Spoken English Mastery',
    instructor: 'Nusrat Jahan',
    rating: 4.8,
    students: 15300,
    price: 1499,
    oldPrice: 2999,
    duration: '3 months',
    lectures: 90,
    tag: 'special',
    badge: 'Popular',
    gradient: 'from-accent-400 to-accent-600',
    emoji: '🗣️',
  },
  {
    id: 6,
    title: 'HSC 26 Chemistry 2nd Paper',
    instructor: 'Rezaul Karim',
    rating: 4.6,
    students: 6450,
    price: 1799,
    oldPrice: 2999,
    duration: '5 months',
    lectures: 120,
    tag: 'fbc26',
    badge: '',
    gradient: 'from-brand-700 to-brand-900',
    emoji: '🧪',
  },
  {
    id: 7,
    title: 'Class 8 Full Syllabus',
    instructor: 'Sumaiya Akter',
    rating: 4.9,
    students: 11200,
    price: 999,
    oldPrice: 1999,
    duration: '12 months',
    lectures: 300,
    tag: 'all',
    badge: '',
    gradient: 'from-brand-500 to-brand-700',
    emoji: '📚',
  },
  {
    id: 8,
    title: 'IBA-DU Admission Premium',
    instructor: 'Tanvir Hasan',
    rating: 4.9,
    students: 3280,
    price: 6999,
    oldPrice: 9999,
    duration: '5 months',
    lectures: 200,
    tag: 'special',
    badge: 'Premium',
    gradient: 'from-brand-800 to-brand-950',
    emoji: '🏛️',
  },
];

export const books = [
  {
    id: 1,
    title: 'HSC Physics MCQ Bank',
    author: 'iEducation Team',
    price: 350,
    pages: 420,
    gradient: 'from-brand-700 to-brand-950',
    emoji: '⚛️',
  },
  {
    id: 2,
    title: 'Admission Math Solver',
    author: 'Rafsan Jamil',
    price: 480,
    pages: 560,
    gradient: 'from-accent-500 to-amber-600',
    emoji: '📐',
  },
  {
    id: 3,
    title: 'SSC English Grammar',
    author: 'Mehnaz Sultana',
    price: 280,
    pages: 320,
    gradient: 'from-brand-500 to-brand-800',
    emoji: '🔤',
  },
  {
    id: 4,
    title: 'Medical Question Bank',
    author: 'Dr. Rifat Ahmed',
    price: 590,
    pages: 640,
    gradient: 'from-brand-600 to-brand-900',
    emoji: '🧬',
  },
  {
    id: 5,
    title: 'Class 8 Bangla Master',
    author: 'Selim Hossain',
    price: 220,
    pages: 280,
    gradient: 'from-brand-800 to-brand-950',
    emoji: '📖',
  },
];

export const teachers = [
  { id: 1, name: 'Tahmid Hasan', subject: 'Physics', exp: '12 yrs', emoji: '👨‍🏫', color: 'from-brand-600 to-brand-900' },
  { id: 2, name: 'Dr. Rifat Ahmed', subject: 'Biology', exp: '15 yrs', emoji: '👨‍⚕️', color: 'from-accent-500 to-amber-600' },
  { id: 3, name: 'Engr. Sajid Khan', subject: 'Math', exp: '10 yrs', emoji: '🧑‍💻', color: 'from-brand-700 to-brand-950' },
  { id: 4, name: 'Nusrat Jahan', subject: 'English', exp: '9 yrs', emoji: '👩‍🏫', color: 'from-brand-500 to-brand-800' },
  { id: 5, name: 'Mahbub Rahman', subject: 'Higher Math', exp: '11 yrs', emoji: '🧑‍🏫', color: 'from-accent-400 to-accent-600' },
  { id: 6, name: 'Rezaul Karim', subject: 'Chemistry', exp: '13 yrs', emoji: '🧑‍🔬', color: 'from-brand-800 to-brand-950' },
];

export const freeResources = [
  {
    id: 'sheet',
    title: 'Free Lecture Sheet',
    subtitle: 'PDF notes & cheat sheets',
    icon: 'FileText',
    gradient: 'from-brand-600 to-brand-900',
    count: '320+ sheets',
  },
  {
    id: 'video',
    title: 'Free Video Class',
    subtitle: 'High-quality video lessons',
    icon: 'Video',
    gradient: 'from-accent-500 to-amber-600',
    count: '480+ videos',
  },
  {
    id: 'quiz',
    title: 'Weekly Quiz',
    subtitle: 'Compete & win rewards',
    icon: 'Trophy',
    gradient: 'from-brand-700 to-brand-950',
    count: 'New every Friday',
  },
];

export const user = {
  name: 'Joy Ahmed',
  email: 'joy.ahmed@iedu.app',
  phone: '+8801711-000000',
  level: 'HSC 2026 - Science',
  joined: 'Jan 2024',
  avatarColor: 'from-brand-700 to-accent-500',
  streak: 18,
  points: 2480,
};
